### ISSUE TITLE
[Not issue but gratitude :) ]

### ISSUE THREAD

**Issue by Johnmcenroyy** [techee/lsp-proxy#1]
Just wanted to thank you @techee  for such a great addition to Geany, I follow your work and git updates. All work wonderful. No problems at all. Now I am using latest possibility to load config. Thanks.

**Comment by techee** [comment]
There actually were some problems which weren't exposed by Python servers but other LSPs. I hope all these are fixed now.

I added the config file and made some of the basic features configurable so they can be used from non-primary servers too. I may make more of them configurable in the future if there's some interest.

Also, I now merge "code actions" so when you right-click in the editor, the Commands submenu shows actions from all the servers and when selected, they are directed to the right server.

I more or less consider the proxy "feature complete" now and don't plan any more development unless there are some bugs or someone requests some feature that makes sense.

**Comment by Johnmcenroyy** [comment]
@techee Thanks again for your work. I will check new features.
